### ISSUE TITLE
When `dockerizeBundler` is enabled, `bundlerArgs` isn't passed to `bundle install`

### ISSUE THREAD

**Issue by sue445** [logandk/serverless-rack#2]
# Context
I add development gems (e.g. `aws-sdk-ec2`, `rspec`) to `Gemfile`.
I don't want to include these gems, so I want to pass `--without` option to `bundle install`.

## serverless.yml
```yml
service: monitoring

plugins:
  - serverless-rack

custom:
  rack:
    dockerizeBundler: true
    bundlerArgs: --without development test
```

## Gemfile
```ruby
source "https://rubygems.org"

git_source(:github) {|repo_name| "https://github.com/#{repo_name}" }

gem "gitlab"

group :development, :test do
  gem "aws-sdk-cloudwatch"
  gem "aws-sdk-cloudwatchlogs"
  gem "aws-sdk-ec2"
  gem "aws-sdk-kms"
  gem "pry-byebug"
  gem "rspec"
end
```

# Expected
* Only runtime gem (e.g. `gitlab`) is included in zip.
* Development gems (e.g. `aws-sdk` gems) aren't included in zip.

# Actual
Development gems are included in zip. `monitoring.zip` is very fat :cry:

```bash
$ cd .serverless/

$ ls -l monitoring.zip
-rw-r--r--  1 sue445  staff  4852659  2 19 10:47 monitoring.zip

$ unzip monitoring.zip -d monitoring

$ ls -l monitoring/vendor/bundle/ruby/2.5.0/gems/
total 0
drwxr-xr-x   3 sue445  staff   96  2 19 10:48 aws-eventstream-1.0.1
drwxr-xr-x   4 sue445  staff  128  2 19 10:48 aws-partitions-1.136.0
drwxr-xr-x   3 sue445  staff   96  2 19 10:48 aws-sdk-cloudwatch-1.13.0

(snip)
```

# What is problem?
When `dockerizeBundler` is enabled, `bundlerArgs` isn't passed to `bundle install`.

* https://github.com/logandk/serverless-rack/blob/57d1a53a6b193f45b9bdec9dd7b5e3f05f2788ed/index.js#L247-L270
* https://github.com/logandk/serverless-rack/blob/57d1a53a6b193f45b9bdec9dd7b5e3f05f2788ed/Dockerfile#L2

**Comment by logandk** [comment]
Thanks for the detailed description, it's fixed in the next version
