### ISSUE TITLE
`#close` not called on response body

### ISSUE THREAD

**Issue by zbristow** [logandk/serverless-rack#26]
It looks like [`format_body`](https://github.com/logandk/serverless-rack/blob/0550bd45512a277dc83cabf62c700469fd00c407/lib/serverless_rack.rb#L130) is not calling `close` on the response body after iterating over it. I found this when trying to use `Rack::CommonLogger` with my app and not seeing the expected log entries show up in my CloudWatch logs. It turns out this middleware relies on `body.close` to be called to emit a log message.

 Since this is part of the [Rack spec](https://github.com/rack/rack/blob/d08cdbe7f940af0d2040fe65965caf1c8c531307/SPEC.rdoc#label-The+Body) to call `close` if the body responds to it, can `format_body` be updated to do this? I was able to get this middleware working after patching locally, so I can submit a PR with a fix if you'd like.

**Comment by logandk** [comment]
@zbristow Thanks for reporting, I'd appreciate a PR, since you already patched locally.
