### ISSUE TITLE
configPath not specified when running locally

### ISSUE THREAD

**Issue by hlarsen** [logandk/serverless-rack#5]
i'm getting an error trying to use configPath along with sls rack serve:
`configuration /home/hlarsen/Source/work/motobot/config.ru not found`

it appears getRackHandlerConfiguration() is only run during packing, which i'm guessing is the problem.

**Comment by logandk** [comment]
Actually, the `configPath` option gets written to `.serverless-rack`, which is included in your deployment bundle. Try looking into your bundle and check that `.serverless-rack` contains the path you're expecting. If the path is correct and `config.ru` exists at that location, please provide steps to reproduce.

**Comment by hlarsen** [comment]
i do see `.serverless-rack` in the .zip when i run `sls package` and it does work in production after i deploy, but when i run `sls rack serve` to test locally i get the error. there isn't a `.serverless` directory generated when i run it; is there another path i should be looking for a .zip/bundle in?
